# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Allan Khariton
description: "I'm a Sr Data & BI Analyst, focused on Operational analytics and automating workflows for senior leaders.  My portfolio focuses on projects I've recently undertaken, with a strong emphasis on business impact and learning new tools & languages. You can view my projects in the posts below, and visit my Github & LinkedIn pages (or download my Resume) by using the links below."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Rockville, MD"
resume_url: /docs/A_Khariton_Resume_2025.08.12.pdf
avatar_image: /img/Head Shot.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/allan-khariton/" # Add your linkedln handle
github: "https://github.com/akstl1"  # Add your github handle

paginate: 8
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



